name: 刷步数

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '40 2 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: 开始
        run: |
          pip install requests
          pmode='${{ secrets.PMODE }}'
          pkey='${{ secrets.PKEY }}'
          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'
          step='${{ secrets.STEP }}'

          python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}

      - name: Send Bark Notification
        env:
          BARK_SERVER_URL: ${{ secrets.BARK_SERVER_URL }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
        run: |
          URLS=$(echo "${{ steps.prepare_urls.outputs.urls }}" | tr ',' '\n')
          TITLE="Xiao Mi Step Done"
          # 构建完整 URL 并发送请求
          curl -X GET "${BARK_SERVER_URL}/${BARK_KEY}/${TITLE}"
