name: 刷步数

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '40 2 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: [self-hosted, VM-16-15-opencloudos]

    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        # with:
        #   python-version: 3.7
      - name: 开始
        run: |
          pip install requests
          pmode='${{ secrets.PMODE }}'
          pkey='${{ secrets.PKEY }}'
          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'
          step='${{ secrets.STEP }}'

          python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}
